import type { DemoStep, Scenario, ViewId } from "./types";

function views(
  internal: [string, string[]],
  review: [string, string[]],
  customer: [string, string[]],
): Record<ViewId, { title: string; lines: string[] }> {
  return {
    internal: { title: internal[0], lines: internal[1] },
    review: { title: review[0], lines: review[1] },
    customer: { title: customer[0], lines: customer[1] },
  };
}

const inspection: Scenario = {
  id: "inspection",
  title: "Inspection and assessment",
  company: "Harborline Assessment",
  summary: "A request arrives with a site, a scope, and a date, and without the access notes a visit needs.",
  evidenceNote: "Sample company. The stage shapes for intake, proposal review, inspection, and reporting exist in the public development source. This page does not run that source. Project setup and billing stay planned.",
  problem: "The request, photos, and approval live in different threads, so nobody can say what is blocking the visit.",
  workflow: "Inquiry, missing-information hold, sample proposal, human review, then a sample job, field notes, report, and invoicing handoff.",
  outcome: "The team can see the next action. Nothing is sent to a customer and no invoice is created.",
  steps: [
    {
      id: "request",
      phase: "Inquiry",
      title: "Request arrives",
      narration: "Harborline receives a roof and envelope assessment request for 18 Cedar Wharf, Port Merrow. The requested date is 18 April. Access notes were not included.",
      evidence: "illustrative",
      evidenceNote: "Website sample. Lead intake is a runtime-backed stage in the public development source, and production use is not activated.",
      gate: "always",
      input: "Address, scope, requested date, and an incomplete note.",
      organized: "Nothing is combined yet. The request is still just the message that arrived.",
      human: "No decision yet.",
      outcome: "The request is waiting to be turned into one intake record.",
      views: views(
        ["Unassigned request", ["Site and scope are visible.", "Access notes are empty.", "No owner has been named."]],
        ["Review queue", ["Nothing is waiting for approval.", "The request has not become a proposal."]],
        ["Customer status", ["We have the request for 18 Cedar Wharf.", "We still need access notes before a visit can be prepared."]],
      ),
      record: {
        title: "Inbound request",
        fields: [
          { label: "Company", value: "Harborline Assessment" },
          { label: "Site", value: "18 Cedar Wharf, Port Merrow" },
          { label: "Scope", value: "Roof and envelope assessment" },
          { label: "Requested date", value: "18 April" },
          { label: "Access notes", value: "Missing" },
        ],
      },
    },
    {
      id: "intake",
      phase: "Qualification",
      title: "Intake record",
      narration: "The address, scope, and date are placed on one intake record. The missing access note stays visible instead of disappearing into the thread.",
      evidence: "development-source",
      evidenceNote: "The public guided scenario treats information check as runtime-backed. This record is still sample data.",
      gate: "always",
      input: "The inbound request.",
      organized: "Site, scope, date, and the gap are fields on one record.",
      human: "A person can add the missing note or leave the record on hold.",
      outcome: "The gap is explicit.",
      views: views(
        ["Intake record", ["One record holds the request.", "Required access notes are marked missing."]],
        ["Review queue", ["No proposal is in review.", "The hold is an information gap, not an approval."]],
        ["Customer status", ["Your request is in intake.", "We are waiting on access notes."]],
      ),
      record: {
        title: "Intake record HA-1044",
        fields: [
          { label: "Record", value: "HA-1044" },
          { label: "Status", value: "Needs information" },
          { label: "Missing", value: "Roof access notes" },
        ],
      },
    },
    {
      id: "gap",
      phase: "Qualification",
      title: "Missing details stop the flow",
      narration: "With access notes still missing, the sample does not prepare a proposal or a visit. A person has to supply the note or consciously continue later.",
      evidence: "development-source",
      evidenceNote: "Information-check holds are part of the public source shape. Turning this on here only changes the sample.",
      gate: "gap",
      input: "Intake record HA-1044 with an empty access field.",
      organized: "The missing field is the current blocker.",
      human: "Someone must add the note. The sample will not invent it.",
      outcome: "Proposal and scheduling stay blocked.",
      views: views(
        ["Hold", ["Next task: collect roof access notes.", "No visit is queued."]],
        ["Review queue", ["This is not an approval.", "It is waiting on a person for information."]],
        ["Customer status", ["We cannot prepare the visit until access notes arrive."]],
      ),
      record: {
        title: "Hold on HA-1044",
        fields: [
          { label: "Blocker", value: "Roof access notes" },
          { label: "Waiting on", value: "A person at Harborline or the customer" },
        ],
      },
    },
    {
      id: "proposal",
      phase: "Proposal",
      title: "Sample proposal",
      narration: "Once the note is present, the sample prepares a proposal for internal review. It is not a price quote and it is not sent.",
      evidence: "development-source",
      evidenceNote: "Proposal drafting and review states exist in the public source. The production catalog is unconfigured. Figures here are not prices.",
      gate: "ready",
      input: "Complete intake record.",
      organized: "Scope, site, and assumptions are collected into proposal version 1.",
      human: "It still needs a reviewer.",
      outcome: "The proposal is ready for a person.",
      views: views(
        ["Draft proposal", ["Version 1 is ready for review.", "No customer delivery is attempted."]],
        ["Review queue", ["Harborline proposal HA-1044-P1 is waiting."]],
        ["Customer status", ["We are preparing the assessment scope. You have not been asked to accept it."]],
      ),
      record: {
        title: "Proposal HA-1044-P1",
        fields: [
          { label: "Status", value: "Ready for review" },
          { label: "Scope", value: "Roof and envelope assessment" },
          { label: "Assumptions", value: "Daytime access, two stories, sample only" },
        ],
      },
      output: {
        title: "Sample proposal excerpt",
        lines: [
          "Site: 18 Cedar Wharf, Port Merrow.",
          "Scope: visual roof and envelope assessment.",
          "This excerpt is synthetic. It is not an offer, a price, or a contract.",
        ],
      },
    },
    {
      id: "review",
      phase: "Approval",
      title: "Human review",
      narration: "A reviewer can approve the sample proposal or send it back. Approving it does not email anyone.",
      evidence: "development-source",
      evidenceNote: "The public source has approve and request-revision. This control only changes the walkthrough.",
      gate: "ready",
      decisionPoint: true,
      input: "Proposal HA-1044-P1.",
      organized: "The proposal is frozen for the decision.",
      human: "Approve the sample, or do not.",
      outcome: "The next step depends on that decision.",
      views: views(
        ["Waiting on review", ["The record will not move itself.", "Use Approve sample proposal or Reject sample proposal."]],
        ["Review queue", ["One item: HA-1044-P1.", "Decision required."]],
        ["Customer status", ["The scope is in internal review."]],
      ),
      record: {
        title: "Review HA-1044-P1",
        fields: [
          { label: "Reviewer", value: "Unassigned sample reviewer" },
          { label: "Decision", value: "Pending" },
        ],
      },
    },
    {
      id: "revision",
      phase: "Approval",
      title: "Approval not granted",
      narration: "The sample stays in revision. Scheduling, field notes, and the report do not start.",
      evidence: "development-source",
      evidenceNote: "Request-revision is a real state in the public proposal model. The words here are sample copy.",
      gate: "rejected",
      input: "Rejected sample proposal.",
      organized: "The proposal is marked revision required.",
      human: "A person has to change the scope before it can be reviewed again.",
      outcome: "The job is not created.",
      views: views(
        ["Revision hold", ["Next action: revise the sample scope.", "No task is scheduled."]],
        ["Review queue", ["HA-1044-P1 left the queue.", "It is not approved."]],
        ["Customer status", ["The scope is being revised. There is no visit yet."]],
      ),
      record: {
        title: "Revision HA-1044-P1",
        fields: [
          { label: "Status", value: "Revision required" },
          { label: "Job", value: "Not created" },
        ],
      },
    },
    {
      id: "job",
      phase: "Scheduling",
      title: "Sample job and scheduled task",
      narration: "After approval, the sample shows a job and a site task. Award-to-project automation is still planned in the source, so this step is a prototype.",
      evidence: "planned",
      evidenceNote: "The public guided scenario marks project setup as deferred. Treat this task as illustrative.",
      gate: "approved",
      input: "Approved sample proposal.",
      organized: "A job shell and one scheduled task.",
      human: "A coordinator still confirms the crew. The sample does not contact them.",
      outcome: "The next action is the site visit, on paper only.",
      views: views(
        ["Job board", ["Job HA-1044-J is a sample.", "Task: site assessment, 18 April, morning window."]],
        ["Review queue", ["No open approval.", "The proposal decision is already recorded in the sample."]],
        ["Customer status", ["An assessment window is prepared in the sample. This is not a confirmed appointment."]],
      ),
      record: {
        title: "Sample job HA-1044-J",
        fields: [
          { label: "Task", value: "Site assessment" },
          { label: "Window", value: "18 April, morning" },
          { label: "Crew", value: "Unassigned sample" },
        ],
      },
    },
    {
      id: "field",
      phase: "Field work",
      title: "Field notes and synthetic sketch",
      narration: "The sample records two field notes and a diagram. It is not a photograph and it was not extracted by a model.",
      evidence: "illustrative",
      evidenceNote: "The public source has an inspection stage. This sketch was drawn for the website sample.",
      gate: "approved",
      input: "Sample task HA-1044-J.",
      organized: "Notes and the sketch are attached to the job.",
      human: "A reviewer still has to accept the report later.",
      outcome: "Evidence is on the record, marked synthetic.",
      sketch: true,
      views: views(
        ["Field log", ["Note: flashing pulled at the north parapet.", "Note: drain is slow. Sketch attached."]],
        ["Review queue", ["Field evidence is not the report.", "Report review comes next."]],
        ["Customer status", ["The sample visit has notes. A report is not released."]],
      ),
      record: {
        title: "Field notes",
        fields: [
          { label: "North parapet", value: "Flashing pulled, sample note" },
          { label: "Drain", value: "Slow, sample note" },
          { label: "Imagery", value: "Synthetic sketch, not a photo" },
        ],
      },
    },
    {
      id: "report",
      phase: "Reporting",
      title: "Report for review",
      narration: "The sample assembles a short report and holds it for a person. It is not delivered.",
      evidence: "development-source",
      evidenceNote: "Report assembly and technical review exist as runtime-backed stages in the public scenario. This text is a website sample.",
      gate: "approved",
      input: "Field notes and the synthetic sketch.",
      organized: "Two findings and one recommendation, in a sample report.",
      human: "Technical review is still required before anyone would share it.",
      outcome: "The report waits. No email is created.",
      views: views(
        ["Report draft", ["Report HA-1044-R1 is in review.", "Delivery is not attempted."]],
        ["Review queue", ["Technical review: HA-1044-R1.", "A person has to release it. This button does not."]],
        ["Customer status", ["A report is in review. You do not have it yet."]],
      ),
      record: {
        title: "Report HA-1044-R1",
        fields: [
          { label: "Findings", value: "2 sample findings" },
          { label: "Status", value: "In review" },
        ],
      },
      output: {
        title: "Sample report excerpt",
        lines: [
          "Finding 1. North parapet flashing is pulled in the sample notes.",
          "Finding 2. The roof drain is slow in the sample notes.",
          "Recommendation. A person reviews this before any customer sees it.",
          "Synthetic. Not a delivered report.",
        ],
      },
    },
    {
      id: "handoff",
      phase: "Invoice readiness",
      title: "Ready for invoicing handoff",
      narration: "After the sample report is approved in the story, the record is marked ready for a person to handle invoicing. No invoice is created.",
      evidence: "planned",
      evidenceNote: "Billing is a guided demonstration in the public source and accounting is not connected.",
      gate: "sync-ok",
      input: "Reviewed sample report.",
      organized: "A handoff packet lists the job and the report id.",
      human: "Accounting stays with a person or with that company's own system.",
      outcome: "The sample says ready. It does not sync.",
      views: views(
        ["Handoff", ["Packet lists HA-1044-J and HA-1044-R1.", "No accounting system is contacted."]],
        ["Review queue", ["The report review is done in the sample.", "Invoicing is a manual handoff."]],
        ["Customer status", ["The sample assessment is complete. Billing is not sent from here."]],
      ),
      record: {
        title: "Handoff packet",
        fields: [
          { label: "Job", value: "HA-1044-J" },
          { label: "Report", value: "HA-1044-R1" },
          { label: "Invoice", value: "Not created" },
        ],
      },
    },
    {
      id: "sync",
      phase: "Invoice readiness",
      title: "Handoff cannot sync",
      narration: "The sample accounting handoff fails. The record stays with a person. Nothing is retried outside this page.",
      evidence: "illustrative",
      evidenceNote: "Prototype exception. The public source does not have a live accounting connector.",
      gate: "sync-fail",
      input: "The same handoff packet.",
      organized: "The failure is stored on the packet.",
      human: "Someone chooses another way to invoice. This page will not.",
      outcome: "Status: waiting on a person. No invoice.",
      views: views(
        ["Sync problem", ["Handoff failed in the sample.", "Next action: a person handles invoicing outside Command Center."]],
        ["Review queue", ["No new approval.", "The blocker is the failed handoff."]],
        ["Customer status", ["The sample assessment is complete. Billing status is not available from this site."]],
      ),
      record: {
        title: "Failed handoff",
        fields: [
          { label: "Status", value: "Sync problem" },
          { label: "Invoice", value: "Not created" },
          { label: "Next action", value: "Person handles invoicing" },
        ],
      },
    },
  ],
};

const fieldService: Scenario = {
  id: "field-service",
  title: "Field service",
  company: "North Pier Mechanical",
  summary: "A repair request is structured, a gap can hold scheduling, and a technician update becomes a customer status.",
  evidenceNote: "Illustrative. The public Command Center source is centered on the inspection-style guided scenario. This field-service path is a website prototype, not a verified production workflow.",
  problem: "The dispatcher, the technician, and the customer each have a different version of the visit.",
  workflow: "Request, structure, scheduling or an information gap, assignment, technician update, customer status, review and follow-up.",
  outcome: "The sample shows one status. It does not dispatch a truck or send a message.",
  steps: [
    {
      id: "request",
      phase: "Inquiry",
      title: "Repair request",
      narration: "North Pier gets a no-heat call for Cedar Court Apartments, Building B, unit 12. The boiler badge number was not included.",
      evidence: "illustrative",
      evidenceNote: "Prototype sample. Not a verified field-service module.",
      gate: "always",
      input: "Site, symptom, and a missing equipment id.",
      organized: "The call is still unstructured.",
      human: "A dispatcher will need the badge number if the gap is enforced.",
      outcome: "The request can be structured next.",
      views: views(
        ["Call intake", ["No-heat, Building B, unit 12.", "Boiler badge missing."]],
        ["Review queue", ["No approval yet."]],
        ["Customer status", ["We have the no-heat request for unit 12."]],
      ),
      record: {
        title: "Call NP-220",
        fields: [
          { label: "Site", value: "Cedar Court, Building B, unit 12" },
          { label: "Symptom", value: "No heat" },
          { label: "Badge", value: "Missing" },
        ],
      },
    },
    {
      id: "structure",
      phase: "Qualification",
      title: "Structured request",
      narration: "The sample splits the call into site, symptom, and the missing badge.",
      evidence: "illustrative",
      evidenceNote: "Prototype. Structuring a request resembles intake in the source, but this scenario was not in that guided path.",
      gate: "always",
      input: "Call NP-220.",
      organized: "Three fields replace the free-form call.",
      human: "The dispatcher decides whether the missing badge blocks the visit.",
      outcome: "The gap is visible.",
      views: views(
        ["Structured job", ["Symptom and site are set.", "Equipment id is open."]],
        ["Review queue", ["Not in review."]],
        ["Customer status", ["We are checking the equipment details for unit 12."]],
      ),
      record: {
        title: "Structured request NP-220",
        fields: [
          { label: "Type", value: "Repair visit" },
          { label: "Blocker", value: "Boiler badge, if required" },
        ],
      },
    },
    {
      id: "gap",
      phase: "Scheduling",
      title: "Scheduling held for the badge",
      narration: "If the badge is required, the sample does not assign a technician. Someone has to find the number.",
      evidence: "illustrative",
      evidenceNote: "Prototype exception: waiting on a person.",
      gate: "gap",
      input: "Structured request with an empty badge.",
      organized: "The hold is the next action.",
      human: "A dispatcher or the building contact supplies the badge.",
      outcome: "No assignment.",
      views: views(
        ["Schedule hold", ["Next action: get the boiler badge.", "No technician is assigned."]],
        ["Review queue", ["Waiting on information, not approval."]],
        ["Customer status", ["We need the boiler badge before the sample visit can be assigned."]],
      ),
      record: {
        title: "Hold NP-220",
        fields: [
          { label: "Waiting on", value: "Boiler badge" },
          { label: "Assignment", value: "Not made" },
        ],
      },
    },
    {
      id: "assign",
      phase: "Scheduling",
      title: "Assignment",
      narration: "With the badge in the sample, a technician task appears. Nobody is actually paged.",
      evidence: "illustrative",
      evidenceNote: "Prototype. Scheduling screens exist in the source and were not treated as production behavior.",
      gate: "ready",
      input: "Complete request.",
      organized: "One assigned visit.",
      human: "The dispatcher still owns the real schedule.",
      outcome: "Sample status: technician assigned.",
      views: views(
        ["Assignment", ["Sample technician: R. Cole.", "Window: today, afternoon. Not a real booking."]],
        ["Review queue", ["No approval required for the assignment in this sample."]],
        ["Customer status", ["A technician is assigned in the sample. This is not a confirmed arrival time."]],
      ),
      record: {
        title: "Visit NP-220-V",
        fields: [
          { label: "Technician", value: "R. Cole (sample)" },
          { label: "Window", value: "Afternoon sample" },
          { label: "Badge", value: "B-441 sample" },
        ],
      },
    },
    {
      id: "update",
      phase: "Field work",
      title: "Technician update",
      narration: "The sample technician reports a failed igniter and a part on the truck. The note is written by the script, not by a model.",
      evidence: "illustrative",
      evidenceNote: "Prototype field update. Not live GPS or a live work order.",
      gate: "ready",
      input: "Assigned visit.",
      organized: "The note is on the visit.",
      human: "A reviewer may still follow up.",
      outcome: "Internal status changes to on site, sample only.",
      views: views(
        ["Technician note", ["Igniter failed.", "Replacement is on the truck in the sample."]],
        ["Review queue", ["The note is not a customer message yet."]],
        ["Customer status", ["A technician update exists in the sample and has not been released."]],
      ),
      record: {
        title: "Update NP-220-V",
        fields: [
          { label: "Finding", value: "Failed igniter, sample" },
          { label: "Part", value: "On the truck, sample" },
        ],
      },
    },
    {
      id: "status",
      phase: "Follow-up",
      title: "Customer status message",
      narration: "The sample drafts a status message. It is not sent.",
      evidence: "illustrative",
      evidenceNote: "Prototype. The public source does not send live customer messages from this website.",
      gate: "ready",
      input: "Technician note.",
      organized: "A short status draft sits next to the note.",
      human: "A person would have to send it. This page does not.",
      outcome: "Draft only.",
      views: views(
        ["Draft message", ["The draft says the igniter was replaced in the sample and heat should be checked.", "Send is not available."]],
        ["Review queue", ["Optional review before any real company would send this."]],
        ["Customer status", ["Sample draft: the igniter was replaced and the heat should be checked. This draft was not delivered."]],
      ),
      record: {
        title: "Status draft",
        fields: [
          { label: "Channel", value: "Not sent" },
          { label: "Text", value: "Sample only" },
        ],
      },
      output: {
        title: "Unsent status draft",
        lines: [
          "Cedar Court unit 12: the sample visit found a failed igniter and replaced it.",
          "Please check the heat. This message was not sent.",
        ],
      },
    },
    {
      id: "follow-up",
      phase: "Follow-up",
      title: "Review and follow-up",
      narration: "The sample closes with a follow-up task for the next morning. It is a reminder on the record, not a calendar invite.",
      evidence: "illustrative",
      evidenceNote: "Prototype follow-up.",
      gate: "ready",
      input: "Unsent status draft.",
      organized: "One follow-up task.",
      human: "Someone at North Pier owns the callback.",
      outcome: "Next action is visible.",
      views: views(
        ["Follow-up", ["Call the unit tomorrow morning in the sample.", "No calendar event is created."]],
        ["Review queue", ["The visit note is ready for a person to close."]],
        ["Customer status", ["The sample visit is done. A follow-up call is planned and not scheduled with you."]],
      ),
      record: {
        title: "Follow-up",
        fields: [
          { label: "Next action", value: "Sample callback" },
          { label: "When", value: "Next morning" },
        ],
      },
    },
  ] satisfies DemoStep[],
};

const recurring: Scenario = {
  id: "recurring",
  title: "Recurring property care",
  company: "Lumen Property Care",
  summary: "A recurring visit has a checklist, an on-site issue, and an approval before the customer update.",
  evidenceNote: "Illustrative. Recurring maintenance is not a separate verified scenario in the public Command Center source. This is a website prototype.",
  problem: "The checklist, the exception, and the customer update are easy to lose between visits.",
  workflow: "Recurring task, assigned visit, on-site issue, approval, customer update, next action.",
  outcome: "The sample keeps the exception and the next visit visible. It does not change a real schedule.",
  steps: [
    {
      id: "task",
      phase: "Project setup",
      title: "Recurring task",
      narration: "Lumen has a quarterly roof-drain check for West Orchard Shops. The sample creates the next occurrence only.",
      evidence: "illustrative",
      evidenceNote: "Prototype. Not a verified recurring engine.",
      gate: "always",
      input: "A quarterly drain check on the sample property.",
      organized: "One occurrence with a due window.",
      human: "A coordinator still assigns it.",
      outcome: "The occurrence exists in the sample.",
      views: views(
        ["Recurring work", ["West Orchard Shops, drain check.", "Due window: first week of the sample month."]],
        ["Review queue", ["No exception yet."]],
        ["Customer status", ["A routine drain check is on the sample plan."]],
      ),
      record: {
        title: "Occurrence LP-77",
        fields: [
          { label: "Property", value: "West Orchard Shops" },
          { label: "Task", value: "Quarterly roof-drain check" },
          { label: "Window", value: "Sample month, week 1" },
        ],
      },
    },
    {
      id: "visit",
      phase: "Scheduling",
      title: "Assigned visit and checklist",
      narration: "The sample assigns A. Shah and lists three checks: north drain, south drain, and photo of the scupper. The photo is not collected.",
      evidence: "illustrative",
      evidenceNote: "Prototype checklist.",
      gate: "always",
      input: "Occurrence LP-77.",
      organized: "Assignee plus checklist.",
      human: "The technician completes the list. The sample does not pretend they did.",
      outcome: "The visit can start.",
      views: views(
        ["Checklist", ["North drain.", "South drain.", "Scupper, sample sketch only."]],
        ["Review queue", ["Nothing to approve yet."]],
        ["Customer status", ["A sample technician is assigned to the routine check."]],
      ),
      record: {
        title: "Visit LP-77-V",
        fields: [
          { label: "Assignee", value: "A. Shah (sample)" },
          { label: "Checklist", value: "3 items" },
        ],
      },
    },
    {
      id: "issue",
      phase: "Field work",
      title: "On-site issue",
      narration: "The south drain is packed with debris and the scupper is cracked in the sample notes. The routine check becomes an exception.",
      evidence: "illustrative",
      evidenceNote: "Prototype exception.",
      gate: "ready",
      sketch: true,
      input: "Checklist in progress.",
      organized: "The failed item is pulled out of the routine list.",
      human: "Repair scope needs a person to approve before the sample continues.",
      outcome: "Status: exception open.",
      views: views(
        ["Exception", ["South drain packed.", "Scupper cracked, sample note.", "Routine closeout is paused."]],
        ["Review queue", ["Exception LP-77-E is about to need a decision."]],
        ["Customer status", ["The routine check found an issue. Details are not released yet."]],
      ),
      record: {
        title: "Exception LP-77-E",
        fields: [
          { label: "Item", value: "South drain and scupper" },
          { label: "Status", value: "Needs a decision" },
        ],
      },
    },
    {
      id: "approval",
      phase: "Approval",
      title: "Exception approval",
      narration: "Approve the sample repair note or leave it unapproved. Neither choice contacts the property.",
      evidence: "illustrative",
      evidenceNote: "Prototype human gate.",
      gate: "ready",
      decisionPoint: true,
      input: "Exception LP-77-E.",
      organized: "The exception waits in the review list.",
      human: "Approve sample, or do not.",
      outcome: "The customer update depends on the decision.",
      views: views(
        ["Decision", ["The repair note cannot move itself."]],
        ["Review queue", ["LP-77-E is the only sample item."]],
        ["Customer status", ["An issue is in review."]],
      ),
      record: {
        title: "Review LP-77-E",
        fields: [
          { label: "Decision", value: "Pending" },
          { label: "Customer update", value: "Not written yet" },
        ],
      },
    },
    {
      id: "declined",
      phase: "Approval",
      title: "Approval not granted",
      narration: "The exception stays open. The customer update is not prepared.",
      evidence: "illustrative",
      evidenceNote: "Prototype exception path.",
      gate: "rejected",
      input: "Unapproved exception.",
      organized: "The item remains in the queue with a clearer state.",
      human: "Someone has to decide again later. The page will not.",
      outcome: "Next action: revisit the exception.",
      views: views(
        ["Still open", ["Customer update blocked.", "Next action: a person revisits LP-77-E."]],
        ["Review queue", ["LP-77-E was not approved."]],
        ["Customer status", ["The routine check is not closed. There is no update to share."]],
      ),
      record: {
        title: "Open exception",
        fields: [
          { label: "Status", value: "Not approved" },
          { label: "Update", value: "Not prepared" },
        ],
      },
    },
    {
      id: "update",
      phase: "Follow-up",
      title: "Reviewed customer update",
      narration: "After approval, the sample writes an update. It stays on the record.",
      evidence: "illustrative",
      evidenceNote: "Prototype. Not delivered.",
      gate: "approved",
      input: "Approved exception.",
      organized: "A short update tied to LP-77-E.",
      human: "Sending it would still be a separate action. It is not offered here.",
      outcome: "The update is visible and unsent.",
      views: views(
        ["Update draft", ["South drain needs a repair visit in the sample.", "Not sent."]],
        ["Review queue", ["The exception decision is recorded.", "The queue item is clear."]],
        ["Customer status", ["Sample update: the south drain needs a repair visit. This was not sent to you."]],
      ),
      record: {
        title: "Customer update draft",
        fields: [
          { label: "Tied to", value: "LP-77-E" },
          { label: "Delivery", value: "Not sent" },
        ],
      },
      output: {
        title: "Unsent customer update",
        lines: [
          "West Orchard Shops: the sample drain check found a packed south drain and a cracked scupper.",
          "A repair visit is the next action in the sample. This note was not delivered.",
        ],
      },
    },
    {
      id: "next",
      phase: "Follow-up",
      title: "Next action",
      narration: "The sample shows the next action: schedule the repair visit, then return to the quarterly checklist. No dates are booked.",
      evidence: "illustrative",
      evidenceNote: "Prototype.",
      gate: "approved",
      input: "Unsent update.",
      organized: "Two next actions, in order.",
      human: "Lumen chooses when the repair happens.",
      outcome: "The operation is readable.",
      views: views(
        ["Next actions", ["1. Schedule the sample repair.", "2. Resume the quarterly checklist after that visit."]],
        ["Review queue", ["Empty in the sample."]],
        ["Customer status", ["The next sample action is a repair visit. It is not booked."]],
      ),
      record: {
        title: "Next actions",
        fields: [
          { label: "Now", value: "Schedule repair, sample" },
          { label: "Then", value: "Resume quarterly check" },
        ],
      },
    },
  ],
};

export const scenarios: Scenario[] = [inspection, fieldService, recurring];

export function scenarioById(id: string): Scenario {
  return scenarios.find((item) => item.id === id) ?? inspection;
}
