export const agentFaqs = [
 { q: 'What does CPL sell?', a: 'CPL sells automated software solutions to business problems. Our ten core offers address defined inquiry, request, guidance, customer-care and staff needs. Custom automation is a separate pathway for a different workflow. We start with a useful business outcome; AI can enable particular steps within the software.' },
 { q: 'Can you help with a workflow outside the ten core services?', a: 'Request a custom automation consultation. We assess your process, desired outcome, available APIs, authorized access, security and technical feasibility, then establish an approved scope, budget, timeline and acceptance checks before implementation. A consultation does not guarantee that every requested process can be automated.' },
 { q: 'Are all custom automations built in Stammer AI?', a: 'Stammer AI is the selected platform for our core voice and chat solutions. A custom workflow may require additional software development or integrations. We assess the approach during discovery; those capabilities are not assumed to be native Stammer features.' },
 { q: 'What does an agent need to know about my business?', a: 'We work with your approved service information, hours, service areas, common questions, and next-step rules. The agent is configured around that information and your workflows. It does not automatically know everything from your homepage.' },
 { q: 'Can we update the answers and how it behaves?', a: 'Yes. CPL reviews changes to business information, tone, qualification questions, and boundaries as part of the agreed management scope. We test important changes before using them in customer conversations.' },
 { q: 'How does setup work?', a: 'We discover the conversation you need, configure the agent, connect the agreed tools, and test realistic situations before launch. You review the information and decisions the agent is allowed to make.' },
 { q: 'Where does the information go?', a: 'These solutions use an agreed email inbox for structured requests, one configured human number for suitable voice transfers, or an existing booking link the customer completes. Your team reviews and acts on the information. Other integrations require a separate scope.' },
 { q: 'What happens when it needs a person?', a: 'We define what is out of scope and the approved next step. An agent can explain that a person needs to review the request and collect relevant follow-up details. Live transfers and human response arrangements depend on the setup.' },
 { q: 'Can it book appointments?', a: 'Booking Assistance explains the appointment and shares your existing booking link. The customer chooses a slot and completes booking there. Autonomous booking, rescheduling and cancellation are outside this starter service.' },
 { q: 'What does it cost?', a: 'Implementation and ongoing management are quoted for your scope, usage needs, and connections. Request a core solution demo or a custom automation consultation to discuss the right scope. There are no published standard prices or unlimited-usage commitments.' },
 { q: 'Are calls recorded?', a: 'Recording, consent notices, retention, phone setup, and transfers are discussed for the particular implementation. Recording is not assumed to be enabled. This website’s examples have no audio and record nothing.' },
 { q: 'What if the agent does not know the answer?', a: 'It should stay within approved information, explain the limitation, and use the configured escalation or follow-up path. We test unknown questions and edge cases; no AI system is guaranteed to be correct every time.' },
];
